### ISSUE TITLE
Use gs instead of convert

### ISSUE THREAD

**Issue by tomjaguarpaw** [junjihashimoto/sixel#4]
On Ubuntu 18.04 I found that I couldn't use `convert` to convert PNG to PDF, because there is some sort of security policy that prevents it.  See [a StackOverflow discussion](https://stackoverflow.com/questions/42928765/convertnot-authorized-aaaa-error-constitute-c-readimage-453) for details. On the other hand, I believe that `convert` just calls `gs`, so `sixel` could use the following command instead:

```
gs -dSAFER -r300 -sDEVICE=png16m -o sixel.png sixel.pdf
```

**Comment by junjihashimoto** [comment]
Fixed in version 0.1.2.3.
