### ISSUE TITLE
Cannot get sixel to work properly

### ISSUE THREAD

**Issue by tomjaguarpaw** [junjihashimoto/sixel#5]
I cannot get `sixel` to work.  As you can see from the screenshot below, my terminal supports sixels and I can use `convert` to show `logo.png`.  The command in the `sixel` README does not work, however.  I have no idea how to debug this.

![screenshot](https://user-images.githubusercontent.com/1951567/82732669-7f571700-9d06-11ea-85f2-2a52dd236d6c.png)

**Comment by junjihashimoto** [comment]
Thank you for your feedback.
What is your terminal?
I am using mlterm on demo.

**Comment by tomjaguarpaw** [comment]
I am running `xterm -ti 340`.

**Comment by junjihashimoto** [comment]
I've understood the cause.
xterm uses a palette having 256 colors every 6 lines.
mlterm is not so.

**Comment by junjihashimoto** [comment]
https://github.com/junjihashimoto/sixel/pull/6 is working on xterm.
![image](https://user-images.githubusercontent.com/2469618/82762690-61400280-9e3d-11ea-92db-92988a1865d7.png)

**Comment by tomjaguarpaw** [comment]
Thanks! It's a bit better.  There is something funny about the colours though.  In case it is useful to you, my xterm says it is version `XTerm(344)`.

![screenshot](https://user-images.githubusercontent.com/1951567/82790683-5d73a680-9e64-11ea-896a-6c3a70f9c493.png)

**Comment by junjihashimoto** [comment]
@tomjaguarpaw 
Could you try following xrdb settings?

```
$ echo "XTerm*decTerminalID: vt340" >> $HOME/.Xresources
$ echo "XTerm*numColorRegisters: 256" >>  $HOME/.Xresources
$ xrdb $HOME/.Xresources
$ xterm
```
Probably the SIXEL palette is 16 colors. This enables 256 colors.

**Comment by tomjaguarpaw** [comment]
Yes, it works!  Thanks.

(Since I prefer not to have global persistent state I used the following instead `xterm -xrm "XTerm*decTerminalID: vt340" -xrm "XTerm*numColorRegisters: 256"`)
